---
title: "GSEA Visualisation"
output: html_document
runtime: shiny
---
---
runtime: shiny
output: html_document
---

```{r echo = FALSE}
library(readr)

simplified_views <- read_rds("data/gsea_simplify_cache.rds")
```

```{r echo = FALSE}
cutoff_values <- names(simplified_views) |> as.numeric() |> sort()
cutoff_step <- diff(cutoff_values)[1]
cutoff_min <- min(cutoff_values)
cutoff_max <- max(cutoff_values)

sliderInput("n_breaks", label = "Simplify cutoff:",
              min = cutoff_min, max = cutoff_max, value = cutoff_min,
              step = cutoff_step, ticks = FALSE)
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(enrichplot)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(clusterProfiler)

make_gsea_graph <- function(data, up=TRUE, min_in_cluster = 2) {

  data |>
    filter(p.adjust<0.05) -> data

  if (up) {
    data |>
      filter(NES>0) -> data
  } else {
    data |>
      filter(NES<0) -> data
  }

  data |>
    pairwise_termsim() -> data_termsim

  data_termsim@termsim |>
    as_tibble(rownames="from") |>
    pivot_longer(
      cols=-from,
      names_to="to",
      values_to="weight"
    ) |>
    filter(from != to) |>
    filter(weight > 0.3) -> data_pairs

  tbl_graph(
    edges = data_pairs,
    directed = FALSE
  ) -> data_graph

  data_graph |>
    activate(nodes) |>
    mutate(component = group_components()) |>
    group_by(component) |>
    mutate(component_size = n()) |>
    ungroup() |>
    filter(component_size >= min_in_cluster) -> data_graph

  set.seed(17434)
  ggraph(
    data_graph,
    layout = "fr"
  ) +
    geom_edge_link(alpha=0.2) +
    geom_node_point(aes(fill=as.factor(component)),pch=21, size=4,show.legend = TRUE) +
    geom_node_text(aes(label=name), repel=TRUE, size=3, colour="black") +
    theme_graph() +
    theme(legend.position = "none") -> plot

  return(list(plot,data_graph))
}
```

```{r echo = FALSE}
renderPlot({
  cutoff_key <- as.character(round(input$n_breaks, 1))
  gsea_results <- simplified_views[[cutoff_key]]

  gsea_up_graph <- make_gsea_graph(gsea_results, up=TRUE)
  gsea_up_graph[[1]]
})
```
